

GET https://nvxkioxo35.execute-api.us-east-1.amazonaws.com/prod/spaces
###

POST https://nvxkioxo35.execute-api.us-east-1.amazonaws.com/prod/spaces
content-type: application/json

{
    "location": "USA"
}
###

GET https://nvxkioxo35.execute-api.us-east-1.amazonaws.com/prod/spaces?id=34
###